### ISSUE TITLE
slick directive settings attribute not working

### ISSUE THREAD

**Issue by jdgomezb** [devmark/angular-slick-carousel#56]
Hi, I'm using this on my view:

```html
<slick settings="slickConfig" dots="true" infinite="true" slides-to-show="1" slides-to-scroll="1" prev-arrow="false" next-arrow="false" center-mode="true" center-padding="30px">
```

and then in my controller I'm using this for the settings:
```javascript
$scope.slickConfig = {
      event: {
        afterChange: function (event, slick, currentSlide, nextSlide) {
          console.log('slick afterChange', 'event:', event, 'slick:', slick, 'currentSlide:', currentSlide, 'nextSlide:', nextSlide);
        }
      }
    }
```

The 'afterChange' event is not being fired or the directive is not getting bond to the settings object?

**Comment by devmark** [comment]
Hello, 

please make a demo. 
You could fork these:

http://codepen.io/aszmyd/pen/LGdoyV
http://plnkr.co/edit/9goFW6?p=preview

**Comment by hamidyfine** [comment]
Hi,
I have exactly the same problem.
codes are here:
`https://jsfiddle.net/hamidyfine/c8drrs8v/`

**Comment by tnfno** [comment]
I have the same problem, it does not look like the settings are read if I put them in the controller, works if I put them in the HTML tag.  No errors if I use a name that is not defined in the controller either.  Have tried to recreate it in Codepen, but there it works as expected.  Same versions of angularjs and slick are used.

The solution is built on Drupal 8 with Bootstrap theme and I had to wrap the angular-slick-carousel code in
`(function ($) {
ANGULAR SLICK JS HERE
})(jQuery);
`

This is a known issue and solutiuon in Drupal or you will get an error that $ is unknow.  Everything else works just fine, just the "settings=" in the tag that does not work, so I cannot see that the issue is here.

Anyone that are better than me at this that can spot where the problem may be?

**Comment by tnfno** [comment]
Ok, I made a silly mistake.  Somehow I got the JS from this project instead https://github.com/vasyabigi/angular-slick

Found the mistake when I looked for "settings" in the js and could not find it.  Probably a mistake down when I NPM'ed the files to the server.

So, this project works about the same forthe simple stuff, although it has been abandoned for 3 years, but are missing some key elements.
