### ISSUE TITLE
how to reinitilize slick

### ISSUE THREAD

**Issue by dbelieves** [devmark/angular-slick-carousel#76]
So, I have slick carousel for my images.

I want the carousel to go fullscreen when i click a button.
I am doing it in fullscreen by adding class
`position:fixed; width:100%; height:100%;left:0;top:0`

but i images are partially shown.

how do I reinitialize slick in this case so that it takes up the new width and height and adjusts accordingly?

**Comment by dbelieves** [comment]
anyone? anything?

**Comment by devmark** [comment]
use ng-if to reinit

**Comment by dbelieves** [comment]
Thank you for your reply.
Can you tell me the code. :|

**Comment by dbelieves** [comment]
Got it. Thanks. :)

**Comment by coldshine** [comment]
example: https://github.com/devmark/angular-slick-carousel#slide-data

**Comment by jalchr** [comment]
> For change slide content, you have to set ng-if to destroy and init it

If works, although not very obvious!

**Comment by fabioel** [comment]
For me the data/carousel is updating, however the rendering of the slides doesn't work properly. It only renders the first 2 properly and all other divs are added underneath (so are not part of the carousel).
So I end up with a couple of rows instead of the nice carousel.
Anyone else having this issue?
Here is a plunker, depicting my problem:
after updating the slides are added as normal divs
https://plnkr.co/edit/sL0otyK5uoslbVWxEHcB?p=preview
